// data.js - Datos de Ventilación Mecánica y CNAF (12 meses)
const data = [
    // ============ JULIO 2026 ============
    { mes: 'JULIO 2026', edad: 76, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'JULIO 2026', edad: 65, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 3 },
    { mes: 'JULIO 2026', edad: 81, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2026', edad: 66, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'JULIO 2026', edad: 69, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2026', edad: 87, sexo: 'MASCULINO', motivo: 'Sin datos', diasVNI: 2, diasCNAF: 0 },
    { mes: 'JULIO 2026', edad: 80, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 3 },
    { mes: 'JULIO 2026', edad: 76, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 4, diasCNAF: 0 },
    { mes: 'JULIO 2026', edad: 79, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'JULIO 2026', edad: 72, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2026', edad: 81, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2026', edad: 82, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 1 },
    { mes: 'JULIO 2026', edad: 58, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2026', edad: 71, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 4, diasCNAF: 0 },
    { mes: 'JULIO 2026', edad: 77, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 4, diasCNAF: 1 },
    { mes: 'JULIO 2026', edad: 68, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2026', edad: 77, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },

    // ============ JUNIO 2026 ============
    { mes: 'JUNIO 2026', edad: 28, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 77, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 2, diasCNAF: 1 },
    { mes: 'JUNIO 2026', edad: 47, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 3, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 73, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 52, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 4, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'JUNIO 2026', edad: 75, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 4, diasCNAF: 3 },
    { mes: 'JUNIO 2026', edad: 52, sexo: 'MASCULINO', motivo: 'Sin datos', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 56, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'JUNIO 2026', edad: 69, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 75, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 4, diasCNAF: 1 },
    { mes: 'JUNIO 2026', edad: 41, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 69, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'JUNIO 2026', edad: 71, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 0, diasCNAF: 4 },
    { mes: 'JUNIO 2026', edad: 60, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 31, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'JUNIO 2026', edad: 68, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 7, diasCNAF: 6 },
    { mes: 'JUNIO 2026', edad: 57, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 90, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'JUNIO 2026', edad: 65, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'JUNIO 2026', edad: 89, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 47, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'JUNIO 2026', edad: 70, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 72, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 51, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'JUNIO 2026', edad: 57, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 6 },
    { mes: 'JUNIO 2026', edad: 29, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 3 },
    { mes: 'JUNIO 2026', edad: 66, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 61, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 56, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'JUNIO 2026', edad: 75, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 69, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JUNIO 2026', edad: 82, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },

    // ============ MAYO 2026 ============
    { mes: 'MAYO 2026', edad: 65, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 2 },
    { mes: 'MAYO 2026', edad: 65, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 4 },
    { mes: 'MAYO 2026', edad: 34, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 3 },
    { mes: 'MAYO 2026', edad: 64, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 24, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 90, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'MAYO 2026', edad: 54, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 4, diasCNAF: 3 },
    { mes: 'MAYO 2026', edad: 83, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 56, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 84, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 3, diasCNAF: 6 },
    { mes: 'MAYO 2026', edad: 71, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 84, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 4, diasCNAF: 1 },
    { mes: 'MAYO 2026', edad: 72, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 3 },
    { mes: 'MAYO 2026', edad: 27, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'MAYO 2026', edad: 50, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 4 },
    { mes: 'MAYO 2026', edad: 70, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 2 },
    { mes: 'MAYO 2026', edad: 41, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 4, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 85, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 3, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 67, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 61, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 2, diasCNAF: 2 },
    { mes: 'MAYO 2026', edad: 54, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 3, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 70, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'MAYO 2026', edad: 66, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'MAYO 2026', edad: 28, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 47, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 4, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 77, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 4 },
    { mes: 'MAYO 2026', edad: 28, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 3, diasCNAF: 0 },
    { mes: 'MAYO 2026', edad: 77, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'MAYO 2026', edad: 66, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 3 },
    { mes: 'MAYO 2026', edad: 73, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 2, diasCNAF: 0 },

    // ============ ABRIL 2026 ============
    { mes: 'ABRIL 2026', edad: 86, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 3 },
    { mes: 'ABRIL 2026', edad: 54, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 59, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 54, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 81, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 70, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 63, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 2, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 71, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 2, diasCNAF: 0 },
    { mes: 'ABRIL 2026', edad: 38, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'ABRIL 2026', edad: 30, sexo: 'MASCULINO', motivo: 'Sin datos', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 34, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 3, diasCNAF: 5 },
    { mes: 'ABRIL 2026', edad: 84, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 69, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 36, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 2 },
    { mes: 'ABRIL 2026', edad: 77, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 3 },
    { mes: 'ABRIL 2026', edad: 60, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 56, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 31, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 58, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 49, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 92, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ABRIL 2026', edad: 45, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 71, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 2 },
    { mes: 'ABRIL 2026', edad: 88, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 2 },
    { mes: 'ABRIL 2026', edad: 80, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 47, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ABRIL 2026', edad: 64, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ABRIL 2026', edad: 39, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 79, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 61, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ABRIL 2026', edad: 66, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ABRIL 2026', edad: 85, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ABRIL 2026', edad: 65, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'ABRIL 2026', edad: 65, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },

    // ============ FEBRERO 2026 ============
    { mes: 'FEBRERO 2026', edad: 63, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'FEBRERO 2026', edad: 15, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'FEBRERO 2026', edad: 71, sexo: 'MASCULINO', motivo: 'Sin datos', diasVNI: 1, diasCNAF: 0 },
    { mes: 'FEBRERO 2026', edad: 72, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 2, diasCNAF: 0 },
    { mes: 'FEBRERO 2026', edad: 62, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 1 },
    { mes: 'FEBRERO 2026', edad: 79, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 5 },
    { mes: 'FEBRERO 2026', edad: 66, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'FEBRERO 2026', edad: 47, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 3 },
    { mes: 'FEBRERO 2026', edad: 74, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 3, diasCNAF: 0 },
    { mes: 'FEBRERO 2026', edad: 71, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'FEBRERO 2026', edad: 56, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'FEBRERO 2026', edad: 70, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 4 },
    { mes: 'FEBRERO 2026', edad: 60, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'FEBRERO 2026', edad: 67, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 3, diasCNAF: 0 },
    { mes: 'FEBRERO 2026', edad: 69, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'FEBRERO 2026', edad: 51, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 3 },
    { mes: 'FEBRERO 2026', edad: 68, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 1 },
    { mes: 'FEBRERO 2026', edad: 53, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'FEBRERO 2026', edad: 80, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 2 },
    { mes: 'FEBRERO 2026', edad: 78, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 2 },
    { mes: 'FEBRERO 2026', edad: 67, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 5 },
    { mes: 'FEBRERO 2026', edad: 58, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'FEBRERO 2026', edad: 52, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'FEBRERO 2026', edad: 70, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },

    // ============ ENERO 2026 ============
    { mes: 'ENERO 2026', edad: 66, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 3 },
    { mes: 'ENERO 2026', edad: 73, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 43, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'ENERO 2026', edad: 70, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 44, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 1 },
    { mes: 'ENERO 2026', edad: 48, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 9 },
    { mes: 'ENERO 2026', edad: 78, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'ENERO 2026', edad: 69, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 75, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 60, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 80, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 88, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 0, diasCNAF: 3 },
    { mes: 'ENERO 2026', edad: 45, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 3 },
    { mes: 'ENERO 2026', edad: 54, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 34, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 2 },
    { mes: 'ENERO 2026', edad: 71, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 69, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 2 },
    { mes: 'ENERO 2026', edad: 77, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ENERO 2026', edad: 72, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 2 },
    { mes: 'ENERO 2026', edad: 73, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ENERO 2026', edad: 73, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 2 },
    { mes: 'ENERO 2026', edad: 83, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 57, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 43, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'ENERO 2026', edad: 69, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 58, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 2 },
    { mes: 'ENERO 2026', edad: 67, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 83, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'ENERO 2026', edad: 15, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 2 },
    { mes: 'ENERO 2026', edad: 64, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },

    // ============ DICIEMBRE 2025 ============
    { mes: 'DICIEMBRE 2025', edad: 63, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 6 },
    { mes: 'DICIEMBRE 2025', edad: 75, sexo: 'Sin datos', motivo: 'Sin datos', diasVNI: 1, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 90, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 1 },
    { mes: 'DICIEMBRE 2025', edad: 39, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 2, diasCNAF: 17 },
    { mes: 'DICIEMBRE 2025', edad: 91, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 75, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 3, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 63, sexo: 'Sin datos', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 85, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 2 },
    { mes: 'DICIEMBRE 2025', edad: 37, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'DICIEMBRE 2025', edad: 89, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 76, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 47, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 54, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 66, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 48, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 2, diasCNAF: 4 },
    { mes: 'DICIEMBRE 2025', edad: 70, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 56, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'DICIEMBRE 2025', edad: 43, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'DICIEMBRE 2025', edad: 70, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },

    // ============ NOVIEMBRE 2025 ============
    { mes: 'NOVIEMBRE 2025', edad: 83, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 58, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'NOVIEMBRE 2025', edad: 73, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 3 },
    { mes: 'NOVIEMBRE 2025', edad: 95, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 3 },
    { mes: 'NOVIEMBRE 2025', edad: 64, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'NOVIEMBRE 2025', edad: 53, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 73, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 71, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'NOVIEMBRE 2025', edad: 81, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 2 },
    { mes: 'NOVIEMBRE 2025', edad: 72, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 70, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 3 },
    { mes: 'NOVIEMBRE 2025', edad: 77, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 94, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 2 },
    { mes: 'NOVIEMBRE 2025', edad: 60, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 43, sexo: 'FEMENINO', motivo: 'Sin datos', diasVNI: 0, diasCNAF: 2 },
    { mes: 'NOVIEMBRE 2025', edad: 75, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 46, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'NOVIEMBRE 2025', edad: 65, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 2 },
    { mes: 'NOVIEMBRE 2025', edad: 73, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 73, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'NOVIEMBRE 2025', edad: 43, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 67, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 3 },
    { mes: 'NOVIEMBRE 2025', edad: 75, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 63, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 4, diasCNAF: 2 },
    { mes: 'NOVIEMBRE 2025', edad: 62, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 4 },
    { mes: 'NOVIEMBRE 2025', edad: 85, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 2 },
    { mes: 'NOVIEMBRE 2025', edad: 70, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'NOVIEMBRE 2025', edad: 54, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 3 },
    { mes: 'NOVIEMBRE 2025', edad: 60, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 78, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'NOVIEMBRE 2025', edad: 61, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },

    // ============ OCTUBRE 2025 ============
    { mes: 'OCTUBRE 2025', edad: 44, sexo: 'Sin datos', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 5 },
    { mes: 'OCTUBRE 2025', edad: 73, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'OCTUBRE 2025', edad: 72, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 4, diasCNAF: 4 },
    { mes: 'OCTUBRE 2025', edad: 55, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 4, diasCNAF: 0 },
    { mes: 'OCTUBRE 2025', edad: 50, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 1 },
    { mes: 'OCTUBRE 2025', edad: 74, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'OCTUBRE 2025', edad: 83, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 7, diasCNAF: 12 },
    { mes: 'OCTUBRE 2025', edad: 65, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 1 },
    { mes: 'OCTUBRE 2025', edad: 63, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'OCTUBRE 2025', edad: 50, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 1 },
    { mes: 'OCTUBRE 2025', edad: 46, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 5 },
    { mes: 'OCTUBRE 2025', edad: 86, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'OCTUBRE 2025', edad: 79, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'OCTUBRE 2025', edad: 63, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 4, diasCNAF: 0 },
    { mes: 'OCTUBRE 2025', edad: 71, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 2 },
    { mes: 'OCTUBRE 2025', edad: 89, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'OCTUBRE 2025', edad: 85, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'OCTUBRE 2025', edad: 74, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 1 },
    { mes: 'OCTUBRE 2025', edad: 47, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'OCTUBRE 2025', edad: 73, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 3 },
    { mes: 'OCTUBRE 2025', edad: 57, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },

    // ============ SEPTIEMBRE 2025 ============
    { mes: 'SEPTIEMBRE 2025', edad: 81, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 70, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 0, diasCNAF: 2 },
    { mes: 'SEPTIEMBRE 2025', edad: 70, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 49, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 72, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 4 },
    { mes: 'SEPTIEMBRE 2025', edad: 74, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'SEPTIEMBRE 2025', edad: 80, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 77, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 3, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 70, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 53, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 53, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 66, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 67, sexo: 'FEMENINO', motivo: 'Sin datos', diasVNI: 1, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 62, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 46, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 75, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 2 },
    { mes: 'SEPTIEMBRE 2025', edad: 84, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 67, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 2 },
    { mes: 'SEPTIEMBRE 2025', edad: 70, sexo: 'Sin datos', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 3 },
    { mes: 'SEPTIEMBRE 2025', edad: 68, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 7 },
    { mes: 'SEPTIEMBRE 2025', edad: 77, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 89, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 65, sexo: 'MASCULINO', motivo: 'Sin datos', diasVNI: 1, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 85, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'SEPTIEMBRE 2025', edad: 73, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 72, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 55, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 64, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 3 },
    { mes: 'SEPTIEMBRE 2025', edad: 74, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 67, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 61, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 3, diasCNAF: 4 },
    { mes: 'SEPTIEMBRE 2025', edad: 83, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 3, diasCNAF: 0 },
    { mes: 'SEPTIEMBRE 2025', edad: 80, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 44, sexo: 'MASCULINO', motivo: 'Sin datos', diasVNI: 0, diasCNAF: 1 },
    { mes: 'SEPTIEMBRE 2025', edad: 59, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },

    // ============ AGOSTO 2025 ============
    { mes: 'AGOSTO 2025', edad: 90, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 5 },
    { mes: 'AGOSTO 2025', edad: 89, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'AGOSTO 2025', edad: 67, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'AGOSTO 2025', edad: 84, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'AGOSTO 2025', edad: 35, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 2, diasCNAF: 0 },
    { mes: 'AGOSTO 2025', edad: 82, sexo: 'Sin datos', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 5 },
    { mes: 'AGOSTO 2025', edad: 57, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 2 },
    { mes: 'AGOSTO 2025', edad: 66, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'AGOSTO 2025', edad: 71, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 2, diasCNAF: 0 },
    { mes: 'AGOSTO 2025', edad: 70, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 7, diasCNAF: 9 },
    { mes: 'AGOSTO 2025', edad: 85, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'AGOSTO 2025', edad: 80, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'AGOSTO 2025', edad: 69, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 1 },
    { mes: 'AGOSTO 2025', edad: 75, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'AGOSTO 2025', edad: 46, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 12 },
    { mes: 'AGOSTO 2025', edad: 54, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'AGOSTO 2025', edad: 55, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'AGOSTO 2025', edad: 71, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 2 },
    { mes: 'AGOSTO 2025', edad: 82, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'AGOSTO 2025', edad: 70, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'AGOSTO 2025', edad: 74, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 2 },
    { mes: 'AGOSTO 2025', edad: 61, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 0, diasCNAF: 1 },
    { mes: 'AGOSTO 2025', edad: 61, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'AGOSTO 2025', edad: 64, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 1, diasCNAF: 0 },
    { mes: 'AGOSTO 2025', edad: 79, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'AGOSTO 2025', edad: 67, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 2 },
    { mes: 'AGOSTO 2025', edad: 58, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 1 },
    { mes: 'AGOSTO 2025', edad: 77, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 0, diasCNAF: 2 },

    // ============ JULIO 2025 ============
    { mes: 'JULIO 2025', edad: 65, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 85, sexo: 'MASCULINO', motivo: 'IRA HIPOXEMICA', diasVNI: 3, diasCNAF: 2 },
    { mes: 'JULIO 2025', edad: 67, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 4, diasCNAF: 3 },
    { mes: 'JULIO 2025', edad: 34, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 76, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 70, sexo: 'MASCULINO', motivo: 'Sin datos', diasVNI: 0, diasCNAF: 1 },
    { mes: 'JULIO 2025', edad: 85, sexo: 'FEMENINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 1 },
    { mes: 'JULIO 2025', edad: 87, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 4 },
    { mes: 'JULIO 2025', edad: 74, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 5 },
    { mes: 'JULIO 2025', edad: 79, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 69, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 49, sexo: 'FEMENINO', motivo: 'IRA HIPOXEMICA', diasVNI: 0, diasCNAF: 3 },
    { mes: 'JULIO 2025', edad: 81, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 67, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 2, diasCNAF: 5 },
    { mes: 'JULIO 2025', edad: 84, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR NO CARDIOGENICO', diasVNI: 11, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 85, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 89, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 3 },
    { mes: 'JULIO 2025', edad: 67, sexo: 'MASCULINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 3 },
    { mes: 'JULIO 2025', edad: 65, sexo: 'FEMENINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 3, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 53, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 2, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 49, sexo: 'FEMENINO', motivo: 'EDEMA PULMONAR CARDIOGENICO', diasVNI: 5, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 65, sexo: 'MASCULINO', motivo: 'IRA HIPERCAPNICA', diasVNI: 1, diasCNAF: 0 },
    { mes: 'JULIO 2025', edad: 81, sexo: 'MASCULINO', motivo: 'OTROS', diasVNI: 0, diasCNAF: 2 }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = data;
}
